### ISSUE TITLE
Sending out broadcast messages

### ISSUE THREAD

**Issue by alydersen** [caligo-mentis/smart-bus#16]
Hi @caligo-mentis!

I'm trying to figure out with the new version how to send out broadcast messages. There is info in the docs on how to receive them, but as far as I can see nothing on sending them. I've tried to set the target to '255.255', but is doesn't seem to function.

Thanks and take care (in these corona-times)

Andreas

**Comment by caligo-mentis** [comment]
Hello Andreas!

Could you give some code examples? How exactly you are trying to send broadcast commands?

**Comment by alydersen** [comment]
I'm basically trying to send out the status of a Universal Switch as a broadcast:
```
{
        target: "255.255",
        command: 0xe01c,
        data: {
          switch: switch,
          status: value
        }
      }
```
But it doesn't seem e.g. the logic controller reacts on that.

Andreas

**Comment by caligo-mentis** [comment]
There are no special methods to send broadcast messages, just use `255.255` as a target, as you have done.

It's possible that logic controller doesn't listen for broadcast messages. Do you have some real HDL device which sends broadcast message and logic controller successfully accepts it?

**Comment by alydersen** [comment]
Hi again,

You are correct - the logic controller doesn't seem to be listening for broadcasts, but expects messages to be sent directly to it. Closing the issue.

Andreas
