### ISSUE TITLE
Node-red compatibility

### ISSUE THREAD

**Issue by Destix** [caligo-mentis/smart-bus#3]
Hello.
Is it possible to change "status" in commands.js to "state" (as example), becouse "status" is a function in node-red?

**Comment by caligo-mentis** [comment]
@Destix could you include sample code with this naming conflict? May be it could be solved without changing source code?

**Comment by Destix** [comment]
It's a conflict with [Node-Red node status](https://nodered.org/docs/creating-nodes/status)
Try to use json path msg.status
Дело было давно, не могу найти место где мне понадобилось это поменять, но если я правильно помню прителает status, прочитать ты его не можешь тк в Node-red есть функция status

**Comment by caligo-mentis** [comment]
Пока не вижу противоречий: класс `Node` из `Node-red` просто должен иметь ссылку на объект `smart-bus` и оборачивать взаимодействие с ним. Конфликт может возникнуть только если попытаться объект `smart-bus` использовать как `Node`.

**Comment by caligo-mentis** [comment]
Closed due to inactivity
