### ISSUE TITLE
More op codes

### ISSUE THREAD

**Issue by mrgadget** [caligo-mentis/smart-bus#6]
Hi,

I've forked this and added a couple more op codes to commands.js which I've found through sniffing traffic to dynamically update the colour of the new colour LED capacitive touch buttons, and also to change the brightness (eg a dusk task to dim all the panels and dawn to wake them up).  There's a small gotcha in that for some odd reason the requests for these two op codes need to come from 253.254 regardless of the target subnet/device id.

Would you be interested in integrating this into your package, or should I stick to my fork?

Thanks,
Ben.

**Comment by caligo-mentis** [comment]
Hi Ben,

Sure, just make a PR

**Comment by mrgadget** [comment]
Done. My first PR - hope I did it right! Cheers.

**Comment by caligo-mentis** [comment]
Done in [v0.6](https://github.com/caligo-mentis/smart-bus/blob/master/CHANGELOG.md#060)
